scss:
  exclude:
    - "../assets/_scss/components/**"
    - "../assets/_scss/core/**"
    - "../assets/_scss/elements/**"
    - "../assets/_scss/lib/*/**"
  NestingDepth:
    enabled: true
    max_depth: 6
    severity: warning
  SelectorDepth:
    enabled: true
    max_depth: 3
    severity: warning
