linters:
  exclude:
    - "src/assets/_scss/vendor/*/**"

  NestingDepth:
    enabled: true
    max_depth: 6
    severity: warning

  SelectorDepth:
    enabled: true
    max_depth: 3
    severity: warning
